"""
init_bill_tables

Revision ID: 0b8a85b2cfc4
Revises: 109d2489d83f
Create Date: 2024-04-08 05:36:44.651645

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b8a85b2cfc4"
down_revision = "109d2489d83f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column(
            "updated",
            sa.DateTime(),
            server_default=sa.text("NOW()::timestamp"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("NOW()::timestamp"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sub_bills",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("bill_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("reference", sa.String(), nullable=True),
        sa.Column(
            "updated",
            sa.DateTime(),
            server_default=sa.text("NOW()::timestamp"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("NOW()::timestamp"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bill_id"], ["bills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "unique_reference_case_insensitive",
        "sub_bills",
        [sa.text("lower(reference)")],
        unique=True,
    )
    op.create_check_constraint("check_positive_total", "bills", "total >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_positive_total", "bills")
    op.drop_index("unique_reference_case_insensitive", table_name="sub_bills")
    op.drop_table("sub_bills")
    op.drop_table("bills")
    # ### end Alembic commands ###
